server:
  port: 8082


spring:
  application:
    name: nlp-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nlp
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671//eureka/